# compile_data.py - Compiler to merge JSON curriculum units into data.js

import os
import json

DIRECTORY = os.path.dirname(os.path.abspath(__file__))
CONTENT_DIR = os.path.join(DIRECTORY, "content")
OUTPUT_FILE = os.path.join(DIRECTORY, "data.js")

JAVA_SYNTAX_DICT = [
  {
    "name": "ArrayList",
    "type": "Collection",
    "desc": "Dynamically resizing array implementation of the List interface.",
    "syntax": "import java.util.ArrayList;\n\nArrayList<Integer> list = new ArrayList<>();\nlist.add(10);           // Add element\nint val = list.get(0);  // Get element by index\nlist.set(0, 20);        // Update element\nlist.remove(0);         // Remove element by index\nint size = list.size(); // Get size"
  },
  {
    "name": "HashMap",
    "type": "Collection",
    "desc": "Key-value pair hashing store. Fast O(1) lookup, insert, and delete.",
    "syntax": "import java.util.HashMap;\n\nHashMap<String, Integer> map = new HashMap<>();\nmap.put(\"Alice\", 25);           // Insert/Update\nint age = map.get(\"Alice\");     // Get value\nboolean hasKey = map.containsKey(\"Bob\"); // Check key\nmap.remove(\"Alice\");            // Delete\nint size = map.size();          // Map size"
  },
  {
    "name": "Stack",
    "type": "Collection",
    "desc": "LIFO stack object. Inherits from Vector (synchronized). Prefer Deque in production.",
    "syntax": "import java.util.Stack;\n\nStack<Integer> s = new Stack<>();\ns.push(100);          // Push element to top\nint topVal = s.pop(); // Pop top element\nint peekVal = s.peek(); // View top element without removing\nboolean empty = s.isEmpty(); // Check empty"
  },
  {
    "name": "Queue / LinkedList",
    "type": "Collection",
    "desc": "FIFO queue structure. Queue is an interface usually instantiated via LinkedList.",
    "syntax": "import java.util.Queue;\nimport java.util.LinkedList;\n\nQueue<String> q = new LinkedList<>();\nq.offer(\"First\");      // Enqueue (adds to rear)\nString head = q.poll(); // Dequeue (removes and returns front)\nString peek = q.peek(); // View front without removing\nboolean empty = q.isEmpty();"
  },
  {
    "name": "PriorityQueue",
    "type": "Collection",
    "desc": "Heap implementation. Keeps elements sorted according to natural ordering or custom Comparator.",
    "syntax": "import java.util.PriorityQueue;\nimport java.util.Collections;\n\n// Min-Heap (default)\nPriorityQueue<Integer> minHeap = new PriorityQueue<>();\nminHeap.add(50);\nint min = minHeap.poll();\n\n// Max-Heap\nPriorityQueue<Integer> maxHeap = new PriorityQueue<>(Collections.reverseOrder());"
  },
  {
    "name": "Arrays helper methods",
    "type": "Utility",
    "desc": "Common static helper operations on arrays like sorting and binary search.",
    "syntax": "import java.util.Arrays;\n\nint[] arr = {5, 2, 8, 1};\nArrays.sort(arr);                 // Sort array in-place\nint idx = Arrays.binarySearch(arr, 8); // Binary search on sorted array\nArrays.fill(arr, -1);             // Fill all values with -1\nString s = Arrays.toString(arr);  // Get string representation"
  }
]

def compile():
    print("Compiling curriculum database...")
    units = []
    
    # Check directory
    if not os.path.exists(CONTENT_DIR):
        print(f"Content directory {CONTENT_DIR} does not exist!")
        return

    # Load units in order
    for i in range(14):
        filename = f"unit_{i}.json"
        filepath = os.path.join(CONTENT_DIR, filename)
        if os.path.exists(filepath):
            try:
                with open(filepath, 'r', encoding='utf-8') as f:
                    unit_data = json.load(f)
                    units.append(unit_data)
                    print(f"Loaded {filename}")
            except Exception as e:
                print(f"Error loading {filename}: {e}")
        else:
            print(f"Warning: {filename} missing!")

    curriculum = {
        "units": units
    }

    # Format into javascript file
    js_content = f"// Generated by compile_data.py\n\n"
    js_content += f"const JavaDSACurriculum = {json.dumps(curriculum, indent=2)};\n\n"
    js_content += f"const JAVA_SYNTAX_DICT = {json.dumps(JAVA_SYNTAX_DICT, indent=2)};\n"

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(js_content)
    
    print(f"Successfully generated {OUTPUT_FILE}!")

if __name__ == "__main__":
    compile()
